### ISSUE TITLE
Launching hbmenu via title override causes a fatal error on some titles

### ISSUE THREAD

**Issue by Mithos23** [exelix11/dvr-patches#1]
Most of the time the issue happens with titles that don't support video capture. Some examples: Puyo Puyo Tetris Demo, Super Smash Bros, Hollow Knight
Fatal error screen for PPT Demo: 
![IMG_20210812_004504](https://user-images.githubusercontent.com/54249738/129113646-8957f5b1-7858-4a9c-a322-8f96d12aa22e.jpg)

However, it seems some other titles that have video capturing enabled like Splatoon 2 are affected as well.

**Comment by jozz024** [comment]
may i ask, are you able to even capture in the games that usually don't support capture(i.e. Super Smash Bros. Ultimate)?

**Comment by exelix11** [comment]
I updated the patches, should be fixed now.
Tested title takeover with several games and normally launching splatoon 2.

Let me know if you still face this issue.
