### ISSUE TITLE
13.1 Support

### ISSUE THREAD

**Issue by exelix11** [exelix11/dvr-patches#10]
Am got updated so new patches are needed, will work on them when i have some free time, hopefully soon.

**Comment by Lesking72** [comment]
This is a "dirty" port made by comparing the 13.0.0 and 13.1.0 binaries and updating the offsets. Tested apps with auto recording, manual recording, recording disabled, and apps that allocate too much memory. Haven't tested games that actively block recording/screenshots or those that add an overlay.

[dvr-patches-13.1.0.zip](https://github.com/exelix11/dvr-patches/files/7479637/dvr-patches-13.1.0.zip)

**Comment by exelix11** [comment]
Thank you, i can't test as I didn't update yet but it's worth posting it here for people who want a workaround till i get some time to do it.
If you just ported the raw bytes keep in mind that there are some jmp instructions, if the relative offsets changed those may break, iirc they're only used for error handling so you may not notice in normal usage.
FYI If you're interested in the internals you can find the explaination for every patch piece in my [patch notes](https://github.com/exelix11/dvr-patches/wiki/Porting-notes).

**Comment by exelix11** [comment]
> I also tested loading the 13.0.0 AM binary via LayeredFS and didn't have problems in normal usage.

I'd reccomend against doing that cause you never know what changed.

Anyway, finally managed to get some time to make the new patch: [atmosphere.zip](https://github.com/exelix11/dvr-patches/files/7492937/atmosphere.zip)
There are a few different bytes from yours but didn't check what changes exactly, I did not test either so let me know if it breaks

**Comment by exelix11** [comment]
Update: the previous version doesn't work, [this one should](https://cdn.discordapp.com/attachments/643455945854156831/907018820290502726/atmosphere.zip)

**Comment by Lesking72** [comment]
Can confirm this patch works.

**Comment by exelix11** [comment]
The patch is now out in releases
