### ISSUE TITLE
Does Not Work With Shin Megami Tensei V

### ISSUE THREAD

**Issue by disavery** [exelix11/dvr-patches#13]
Black Screen on SysDVR app (PC), game runs fine

**Comment by exelix11** [comment]
Asked another person to test and they confirmed it works fine so i'd say you didn't install the patches properly. 

Download latest release, inside the zip there is an `atmosphere` folder, copy it to the root of your sd card so it merges with the `atmosphere` folder that you should already have, then reboot the console.

**Comment by disavery** [comment]
you’re correct, my switch was only rebooted into hekate. A full restart fixed my issue. Thank you friend

**Comment by exelix11** [comment]
You also opened #14, can you check if it's the same for that?

**Comment by disavery** [comment]
I have just returned home from a trip, and have confirmed that rebooting into hekate did not apply the patches. A full power down was required.

Both games are streaming to the SysDVR app. Thank you
