### ISSUE TITLE
Game incompatibilty 13.2 

### ISSUE THREAD

**Issue by liuwudi0606** [exelix11/dvr-patches#15]
1.The Witcher 3 can not launch until I delete AM.
2.With 13.2firmware,streaming by usb dose not work.TCP can work but when stop streaming and then I want to stream by TCP again,it reports a QR code until I reboot or I can not use sysdvr again.It means that if I stream successfully and exit,next time I have to reboot.

**Comment by exelix11** [comment]
You're mixing things up a bit here, i'll answer in order

> 1.The Witcher 3 can not launch until I delete AM.

Patches are not supported for that game as you saw in the other issue, nothing that can be done here.

> 2.With 13.2firmware,streaming by usb dose not work.

This is a problem with your setup probably you installed the wrong driver 

> TCP can work but when stop streaming and then I want to stream by TCP again,it reports a QR code until I reboot or I can not use sysdvr again.It means that if I stream successfully and exit,next time I have to reboot.

You don't have to stop streaming in the settings, if nothing is connected sysdvr won't do anything. Anyway when you get the QR screen usually launching a compatible game fixes it.  (Actually there seems to be a bug that sometimes it needs a reboot but that's rare and i can't reproduce it)
