### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by FieryMewtwo** [exelix11/dvr-patches#17]

**Comment by exelix11** [comment]
Not sure about this one, problem is this is not exactly code so i'm not sure if the licenses i use elsewhere apply here.

May i ask what do you intend to do with it ?

Anyway will do some research, it's either going to be gpl2 to match sysdvr and if that's not applicable will look into something else (creative commons maybe ?).

**Comment by FieryMewtwo** [comment]
I wanted to redistribute it.

**Comment by FieryMewtwo** [comment]
Unmodified, with your handle and such listed

**Comment by exelix11** [comment]
I've chosen the BSD 3-Clause License which seems to be ok for this.

> I wanted to redistribute it.

Just add a link to this repo somewhere and it's fine.
