### ISSUE TITLE
Not working with Project Diva: Mega Mix on 13.2.1

### ISSUE THREAD

**Issue by inumugi** [exelix11/dvr-patches#19]
Installed these patches and there is no output for Mega Mix on 13.2 ... issue #7 has a patch but seems to be outdated.

**Comment by swigz27** [comment]
Seems to be working perfectly fine on 14.1.1
![image](https://user-images.githubusercontent.com/30056568/188959091-03339091-b709-4d53-9462-2780501530cd.png)
Maybe give these patches a try? https://github.com/oocyberkevinoo/IPSwitch-MegaMix-Patches
should make the entire thing work just fine
