### ISSUE TITLE
Incompatible with Groove Coaster: Wai Wai Party

### ISSUE THREAD

**Issue by alexfromcanada** [exelix11/dvr-patches#2]
Doesn't seem to work with groove coaster.

No video or audio is streamed.

**Comment by exelix11** [comment]
Took a look at the demo of the game, it has screenshots disabled in the nacp and this seems to prevent recording even with this patch. The youtube app has the same issue.

Currently i don't know how to fix it but will look into it.

**Comment by exelix11** [comment]
Figured out how to patch that as well.  Download the new patches and it should work.
I only tested the demo and the youtube app but i assume it should work on the full game as well.
