### ISSUE TITLE
Can you add a switch to the plug-in on the console？

### ISSUE THREAD

**Issue by zf021600** [exelix11/dvr-patches#21]
Can you add a switch to the plug-in on the console to close the plug-in at any time in unsupported games? It is very troublesome to delete files every time to run some games that do not support this plug-in.

**Comment by exelix11** [comment]
dvrpatches is a patch for a system component, to enable/disable it you always need to reboot the console.

You can simply use any file manager to move the am folder outside or inside of the atmosphere folder and then reboot.
May consider adding a way to automate this to sysdvr settings but you will still need to reboot.

**Comment by zf021600** [comment]
> dvrpatches is a patch for a system component, to enable/disable it you always need to reboot the console.
> 
> You can simply use any file manager to move the am folder outside or inside of the atmosphere folder and then reboot. May consider adding a way to automate this to sysdvr settings but you will still need to reboot.

Looking forward to the new version, thank you for your efforts

**Comment by HeyItsJono** [comment]
Would also appreciate the ability to specifically toggle this on/off (understanding that a reboot is required), as I have other patches in the `am` folder and it's difficult to remember which specific patch filenames are from dvr-patches and which are from other things!

**Comment by exelix11** [comment]
Why do you have other patches in the am folder, the name is arbitrary you can create a new folder with whatever name to put patches from other sources.
Even if i added toggling capabilities to the sysdvr settings app it would still toggle the whole am folder cause hardcoding the list of files sounds rather annoying to maintain.

**Comment by Nazosan** [comment]
Would it be any more feasible if, instead, there was some sort of blacklist rather than a full toggle on/off?  Like a simple flag file in the game's appropriate contents/titleid folder.  Or, conversely, a whitelist with a flag enabling instead (which is more troublesome but still would work.)  I don't know how much can be done via this sort of method, so perhaps this is completely infeasible, but I thought it might at least be easier than a full patch on/off mechanism.

**Comment by exelix11** [comment]
Not possible, dvr patches are system wide, you need a reboot every time to enable or disable them.

Also don't really see the point since afaik the witcher 3 is the only game that crashes when they're active.

**Comment by exelix11** [comment]
Update on this: this feature is coming with the next update of the sysdvr settings app, it will be able to download the latest version of the patches from github and to uninstall them.
Each operation will still require a reboot.

**Comment by exelix11** [comment]
This is now available in SysDVR settings for latest release 5.4
