### ISSUE TITLE
Suddenly Super Smash Brothers Ultimate error message

### ISSUE THREAD

**Issue by Semsemboy** [exelix11/dvr-patches#26]
Super Smash Brothers Ultimate suddenly shows an error message when launched. Worked fine with dvr-patches before but not anymore

**Comment by exelix11** [comment]
I don't recall any new update being released recently so i think it's on your end. Did you install any new game mod or sysmodule ?

**Comment by Semsemboy** [comment]
I have one mod installed and some sysmodules but it worked with them just fine too

**Comment by Semsemboy** [comment]
Also in the tesla overlay sysdvr is constantly stuck at switching when switching from usb to OFF

**Comment by Semsemboy** [comment]
Appearently it's the modpacks fault. I deleted it and everything works again... Even after deleting the dvr-patches it still didnt work but without the modpack it does again so it's not the patches's fault
