### ISSUE TITLE
Patches disable recording in all applications

### ISSUE THREAD

**Issue by Martmists-GH** [exelix11/dvr-patches#27]
After updating (latest dvr-patches after deleting old files, latest HOS (14.1.1), latest Atmosphere (1.3.2)) I am no longer able to record in any game, even in those that already supported it.
It simply says "Unable to take a video capture."

**Comment by exelix11** [comment]
Well this is weird, does it happen even if you remove the patches? Could it be some other factor like memory full or sd corruption?

**Comment by Martmists-GH** [comment]
Removing the patches the issue seems to persist. According to nxdumptool, 44.5 GiB of space is still available on the SD card. I googled a bit, but couldn't seem to find any other people with this issue.

**Comment by exelix11** [comment]
Sorry no clue but doesn't seem to be related to dvrpatches
