### ISSUE TITLE
Crashes atmosphere when opening Tinfoil 12.1

### ISSUE THREAD

**Issue by alexfromcanada** [exelix11/dvr-patches#3]
When opening Tinfoil 12.1 with the patch running, it crashes as below.
![20210811_230607](https://user-images.githubusercontent.com/72053882/129146362-c6540ef0-91bb-44f1-9c7b-2046b5e32a36.jpg)

**Comment by exelix11** [comment]
There's another issue with the same error code which seems to affect all homebrew #1 so think this is a duplicate.
In case it's not, Installable NSPs are not supported by aynone in the community so i guess you're out of luck.
