### ISSUE TITLE
All hb apps crash in 15.0.0

### ISSUE THREAD

**Issue by Semsemboy** [exelix11/dvr-patches#31]
Since updating to 15.0.0 all the hb apps crash in full ram mode due to the newest dvr-patches. Error message with the code 0100000000000023. Only way for me to fix it was delete the patches. Reinstalling them caused crashes again. Everything else works fine and has been updated

**Comment by exelix11** [comment]
Thank you for reporting this, i can confirm this issue but only for certain apps:
Splatoon 2 (nacp recording type manual) and Mario odyssey (nacp recording type auto) work fine with title takeover.
Smash bros (nacp recording disabled) crashes.

Might have to do with memory usage and how much memory libnx allocates by default or i might have forgotten something while porting the patches, will have to do some tests.

**Comment by exelix11** [comment]
[8A94FE28430F4D964F607B7E223D1677289D3BEE000000000000000000000000.zip](https://github.com/exelix11/dvr-patches/files/9846325/8A94FE28430F4D964F607B7E223D1677289D3BEE000000000000000000000000.zip) this patch should solve the issue, can you confirm ?

**Comment by LorenzoMS** [comment]
Had the same issue and can confirm that the patch you put out solves it. Thanks!

**Comment by exelix11** [comment]
Thank you for testing, i made a new release with the fix.
