### ISSUE TITLE
Don't work with Aot2 and jump force 

### ISSUE THREAD

**Issue by SerShiniku** [exelix11/dvr-patches#32]
it's normal? pls help me

**Comment by exelix11** [comment]
I can't provide support for all games, make sure you installed dvr-patches correctly and that you're on a supported firmware then reboot your console.

If it still doesn't work i'll leave this issue open for anyone who wants to look into these games and make a patch.

**Comment by c01dc0ffee** [comment]
JUMP FORCE Deluxe Edition confirmed working with FW 15.0.0, Atmosphere 1.5.2, SysDVR 5.5 and [this version of patches](https://github.com/exelix11/dvr-patches/releases/tag/fw-15.0-fix).
