### ISSUE TITLE
[Help] Tony Hawk's Pro Skater 1+2 not working

### ISSUE THREAD

**Issue by DarrenWarrenV** [exelix11/dvr-patches#33]
I already tried with patches: https://github.com/exelix11/dvr-patches but game doesn't work/isn't compatible. If someone would be able to fix the issue. I love this game :/

**Comment by c01dc0ffee** [comment]
This is confirmed working for me with FW 15.0.0, Atmosphere 1.5.2, SysDVR 5.5 and [this version of patches](https://github.com/exelix11/dvr-patches/releases/tag/fw-15.0-fix).

Make sure you're installing the right patches for your firmware and reboot after installing them. Also try running supported games to rule out a problem with SysDVR.

**Comment by exelix11** [comment]
Thank you for the update, this is probably an user issue then

**Comment by DarrenWarrenV** [comment]
I just checked it after updating to 16.0.0, getting the newest patches and it works! I really, really have no idea why it didn't work before (on 15.0.1), because I did everything right. Anyway, THANK YOU for letting me now, I can play it now wirelessly on a big screen!!!
