### ISSUE TITLE
[Xenoblade 2] does not working

### ISSUE THREAD

**Issue by foxfire881** [exelix11/dvr-patches#34]
the last version of SysDVR on firmware 14.1 works fine with Xenoblade 2. but after I upgrade to firmware 15.0.1 and the newest version of SysDVR, it can't work now, please fix it, thanks~

**Comment by exelix11** [comment]
Did you also happen to update to latest atmosphere version ?

**Comment by foxfire881** [comment]
> 

yes, after I update to latest atmosphere, it is back to normal. 

thanks for your hard work, sysdvr is amazing ~  I dream there is a client app for iOS, so we can play ns on iPad with bigger screen.

**Comment by exelix11** [comment]
Unfortunately apple makes developing things for ios needlessly complicated unless you are already deep in their ecosystem. And as for android its programming model is plain stupid.

I'm not fit for making mobile apps, a third party mobile client is up for grabs, at most i can provide support with the custom protocol.
