### ISSUE TITLE
Not compatible with Switch ver 16.0

### ISSUE THREAD

**Issue by oasis-sharp** [exelix11/dvr-patches#35]
I'm not sure if anyone has tested/reported this yet, but I thought I would let the dev know that currently attempting to launch CFW with dvr patches enabled the switch will crash on boot from my testing. 

This is on the latest Atmosphere beta

**Comment by exelix11** [comment]
Dvr-patches shouldn't crash the console on update. 
You probably have a theme or some sysmodule that's misbehaving.

Either way i'll be adding support for 16.0 soon enough
