### ISSUE TITLE
Fully bricked my switch when installing

### ISSUE THREAD

**Issue by Falakk** [exelix11/dvr-patches#37]
When i installed the files onto my switch, and rebooted it, my switch booted up to the switch logo but then crashed to the atmosphere logo with the error code 2168-0002
I've deleted the folder from my sd card itself and even deleted a binary folder in the atmosphere folder that some people on reddit with the same error got but didnt work either, i noticed that it hasnt been updated for 16.3 yet so thats why im guessing but how do i get it to boot up again? it's been like this for an hour now and im so confused

**Comment by exelix11** [comment]
Not all firmware versions need an update, current works fine with latest release.

As for your console you probably messed up your atmosphere installation, delete everything from your SD card and reinstall atmosphere from scratch
