### ISSUE TITLE
Firm 17.0.0

### ISSUE THREAD

**Issue by lowburger** [exelix11/dvr-patches#38]
Hi,

I may ask there will be support for firm 17.0.0?

Thx your great work for Switch!

**Comment by exelix11** [comment]
I finished working on it but did not test it
[this is the file](https://github.com/exelix11/dvr-patches/files/12906244/A314886778C19B34168EEF92C6058DEBDD5EC4BD000000000000000000000000.zip). I also posted it on discord. WIll upload it as a release in a few days once i get enough feedback.

**Comment by lowburger** [comment]
Great thx! As I test so far all works well.

**Comment by exelix11** [comment]
The release is now up
