### ISSUE TITLE
doesn't work with melonds

### ISSUE THREAD

**Issue by thankyoumomo** [exelix11/dvr-patches#40]
melonDS
0104449009444001
1.0.0

(NSP from: https://gbatemp.net/threads/homebrew-nsp-forwarder-for-firmware-12-0-0.588005/)

**Comment by thankyoumomo** [comment]
it worked when I booted it from the hbmenu,
my bad :O

**Comment by exelix11** [comment]
There is no support for NSP homebrew, you should use atmosphere's title takeover feature which usually works fine.
