### ISSUE TITLE
Crash on The Witcher 3 

### ISSUE THREAD

**Issue by Grayjks** [exelix11/dvr-patches#43]
Hi, i have install the newest version and everytime i open the witcher, start the game 1 got crashed. i delete the patch and game work again. hope u can fix that for this game :D 
i use firmware 18.1.0
[Atmosphère 1.7.1]
Game The witcher 3 US Version
TID: 0100E6701292400
PID: 139
BID: B151A224A429F9A7
Update 4.04b
included all DLC
![455313908_3710094132572850_5318411853461744038_n](https://github.com/user-attachments/assets/7f8af78f-f8e8-46c4-9181-2cc6912e50e5)

**Comment by exelix11** [comment]
This is a known issue, unfortunately it's not a simple fix. #4
