### ISSUE TITLE
19.0 support

### ISSUE THREAD

**Issue by exelix11** [exelix11/dvr-patches#44]
Here's a test patch for 19.0: https://cdn.discordapp.com/attachments/643455945854156831/1297215897794248795/003B99F2447E33B6D814B799D4F9E16BC09FDFF6000000000000000000000000.ips?ex=67151df3&is=6713cc73&hm=a87d522751c099f03ae840bf1a304c38a99dae70dfc6880f79daca4849e35156&

I only tested it in a few games, please provide feedback if it cause issues. I expect to push it to the repo within the next few days.

To install it copy it to `/atmosphere/exefs_patches/am/` the file name is `003B99F2447E33B6D814B799D4F9E16BC09FDFF6000000000000000000000000.ips`, this is important don't change it.

**Comment by DevanWolf** [comment]
> Here's a test patch for 19.0:

Your link has expired. Please upload the file directly here or use a different file sharing site like Catbox.

**Comment by exelix11** [comment]
[003B99F2447E33B6D814B799D4F9E16BC09FDFF6000000000000000000000000.zip](https://github.com/user-attachments/files/17458067/003B99F2447E33B6D814B799D4F9E16BC09FDFF6000000000000000000000000.zip)

**Comment by exelix11** [comment]
Note that an user reported Hyrule Warriors Age of Calamity crashing with this when previously on 18.0 with dvrpatches it was working fine. I'll check again the patches but it's possible that something changed in the firmware that causes games to get less memory, i'll wait a little more for more reports.

**Comment by Punknpc** [comment]
I have tried with Smashbros for a good 3h session, and it works fine, 0 problems for me.

**Comment by ELY3M** [comment]
its working :)

**Comment by exelix11** [comment]
Turns out the previous patch is broken and causes crashes in some games that display a watermark on recordings, this one should fix it.  [003B99F2447E33B6D814B799D4F9E16BC09FDFF6000000000000000000000000.zip](https://github.com/user-attachments/files/17528173/003B99F2447E33B6D814B799D4F9E16BC09FDFF6000000000000000000000000.zip)

If all is well i'll push it to releases tomorrow.

**Comment by exelix11** [comment]
This is now released
