### ISSUE TITLE
Doesn't work with "Tsukihime -A piece of blue glass moon-"

### ISSUE THREAD

**Issue by xOrieus** [exelix11/dvr-patches#5]
Hi, I installed and tried the patch, it worked with Smash Ultimate but for this game it didn't, the game came out yesterday (august 25) I've read the other open issue so, here's the info if anyone can take a look, thanks

Name: 月姫 -A piece of blue glass moon-
TID: 01001DC01486A000
Update: v65536 (0.0.1.0) (01001DC01486A800)

**Comment by exelix11** [comment]
Finally got some time to work on this, i may have an idea on how to fix this but i don't have the game to test, if you're still interested could you test a new patch for me ? Need to know your firmware version.

**Comment by xOrieus** [comment]
Sure thing, i'm using Firmware version 12.1.0 and AMS 1.0.0

**Comment by exelix11** [comment]
Can you try if [this patch](https://github.com/exelix11/dvr-patches/files/7164825/am.zip) works ? extract and replace the one with the same name you already have then reboot the console.

**Comment by xOrieus** [comment]
I deleted the old "am" folder and replaced with this patch you send me and IT WORKED!, tested it with Tsukihime and Smash Ultimate, worked on both, thanks

**Comment by exelix11** [comment]
Great, will make a proper release tomorrow then.
