### ISSUE TITLE
Doesn't work with Disgaea 5 Complete

### ISSUE THREAD

**Issue by QuattroTaii** [exelix11/dvr-patches#6]

**Comment by exelix11** [comment]
Took a look at the demo, the game hardcodes the amount of memory it needs, malloc fails and it crashes on a null pointer dereference.

To fix patch `MOV W19, #0xBC000000` to `MOV  W19, #0xB5C00000` at the very start of nnMain, i don't have the full game so i'm only providing a [patch for the demo](https://github.com/exelix11/dvr-patches/files/7161486/demo.patch.zip) anyone feel free to port it to the full version.

**Comment by QuattroTaii** [comment]
Thank you so much for looking into this! I'll port it myself but I don't know how. Is there some documentation somewhere on how to do this?

**Comment by exelix11** [comment]
If you're not into programming and in particular not into reverse engineering it's not exactly easy. 
To summarize you have to extract the exefs of the game, disassemble it, find the instruction i mentioned, patch it and create an ips file
Guess if you DM me on discord i could lend you a hand.

**Comment by exelix11** [comment]
[Here's a patch for the latest update of the full game](https://github.com/exelix11/dvr-patches/files/7176667/patch.zip). 
Not sure if i should add this to the repo in a games folder, for now will keep this issue open.

**Comment by Fatih120** [comment]
Confirming here that this patch still works. Thank you.
