### ISSUE TITLE
Appears not to work with Project Diva Megamix

### ISSUE THREAD

**Issue by Ryuhouji** [exelix11/dvr-patches#7]
I've attempted several times to get project diva to work with this, and there's just no output. Trying to long-press the record button says "Videos cannot be captured for this software." Hoping to see a patch for this, because i'd like to stream the game in discord for fun.

**Comment by exelix11** [comment]
Can you try the new patch in #5 ?

**Comment by exelix11** [comment]
Downloaded the demo and it seems to work fine.
