### ISSUE TITLE
Does not work on 13.0

### ISSUE THREAD

**Issue by IKEASSB** [exelix11/dvr-patches#8]
I'm assuming that the default DVR stuff Nintendo has must've changed in the new update, so that means that this needs updating too as I can't take videos on Smash anymore.

**Comment by exelix11** [comment]
[Made a patch for 13.0](https://github.com/exelix11/dvr-patches/files/7196373/fw13.zip) this also includes the fix from #5
As i haven't updated yet need some people who can test, in particular need at least three games:

- Auto recording games shouldn't be broken (example: mario odyssey)
- Manual recording games shouldn't be broken (example: splatoon 2)
- Games with recording disabled should work, both modern (example: smash bros) and early ones (example: fast rmx or any other launch game, several have a demo on the eshop)

Guess the more games you can launch without crashes the best.

**Comment by IKEASSB** [comment]
ah alr, i'll test it on some stuff and let you know tomorrow

**Comment by IKEASSB** [comment]
hm doesn't seem to work for me on smash or hulu

**Comment by exelix11** [comment]
Several people reported smash works, it's probably on your side. About hulu idk but if broken won't add support to avoid copyright problems.

**Comment by IKEASSB** [comment]
hm od, i may have put it in the wrong place then, mind sending the file path if possible?

**Comment by ToasterDEV** [comment]
I can also confirm it working with both Smash and Xenoblade Chronicles 2, currently with no issues aside from some artifacting (assuming compression artifacts).

**Comment by exelix11** [comment]
This patch is now available as a release
